[build]
  publish = "."
  command = "npm run build"

[build.environment]
  NODE_VERSION = "16"

[[headers]]
  for = "/*.js"
    [headers.values]
    Content-Type = "application/javascript; charset=utf-8"
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.css"
    [headers.values]
    Content-Type = "text/css; charset=utf-8"
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.json"
    [headers.values]
    Content-Type = "application/json; charset=utf-8"
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.html"
    [headers.values]
    Content-Type = "text/html; charset=utf-8"
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/sw.js"
    [headers.values]
    Content-Type = "application/javascript; charset=utf-8"
    Cache-Control = "public, max-age=0, must-revalidate"
    Service-Worker-Allowed = "/"

[[headers]]
  for = "/manifest.json"
    [headers.values]
    Content-Type = "application/json; charset=utf-8"
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/*.png"
    [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.svg"
    [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*"
    [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "default-src 'self' https: blob: data:; script-src 'self' 'unsafe-inline' 'unsafe-eval' https: blob: cdnjs.cloudflare.com; style-src 'self' 'unsafe-inline' https: cdnjs.cloudflare.com; font-src 'self' https: data: cdnjs.cloudflare.com; img-src 'self' data: https: blob:; connect-src 'self' https: blob: data:; worker-src 'self' blob:;"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Access-Control-Allow-Origin = "https://cdnjs.cloudflare.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
  conditions = {Response = {status = [404]}}

[[redirects]]
  from = "/manifest.json"
  to = "/manifest.json"
  status = 200
  force = true

[[redirects]]
  from = "/sw.js"
  to = "/sw.js"
  status = 200
  force = true
